Build ipxe.iso binary
tinkerbell/ipxedust pull request #67
Opened 2023-02-10 18:52 UTC by fintelia

## Description

Updates the build scripts to also produce an amd64 ipxe.iso binary. Once the CI has generated the binary, I'll make a follow-up PR to expose it from the ipxedust server.

## Why is this needed

An ISO file is another useful file format for booting servers. In particular, it is required to boot using a virtual cdrom drive.

## How Has This Been Tested?

Used the scripts to build an ISO and then booted a Dell server using it.

## How are existing users impacted? What migration steps/scripts do we need?

Adds about 2 MB to ipxedust.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

2023-02-10 23:02 UTC, jacobweinstock requested changes
Is the `ipxe.iso` file included in this intentional? It's an empty file. ~~Also, as it looks like you've not added this to be embedded, what do you think about dropping the changes to `binary/script/build_and_pr.sh`?~~ 

doh, sorry. I need to read the PR description better. I see you want to come back around for the embedded stuff.

2023-02-10 23:50 UTC, fintelia commented
I intentionally included an empty `ipxe.iso` file with the hope that the CI would be more likely to notice it needs to rebuild the binaries. Though looking closer, I think that adding the two scripts to the tracked_files list should be enough to trigger a rebuild. Either way, that empty file will be replaced by an actual ipxe binary, at which point the distinction should not matter.

2023-02-17 19:13 UTC, fintelia commented
Is there anything more for this? It will be particularly helpful combined with https://github.com/tinkerbell/rufio/pull/79 which lets you specify the URL of an ISO for a server to boot from

2023-02-28 18:56 UTC, fintelia commented
Did you mean to merge this?

2023-02-28 21:44 UTC, jacobweinstock approved these changes

2023-02-28 21:44 UTC, jacobweinstock commented
> Did you mean to merge this?

ah, apologies. yes.

2023-02-28 21:44 UTC, merged

2023-03-01 00:00 UTC, fintelia commented
It seems the CI created a new branch [here ](https://github.com/tinkerbell/ipxedust/tree/update_iPXE_2023_02_28_21_45_20) but somehow missed including the new ipxe.iso file?

2023-03-01 00:44 UTC, jacobweinstock commented
> It seems the CI created a new branch [here ](https://github.com/tinkerbell/ipxedust/tree/update_iPXE_2023_02_28_21_45_20) but somehow missed including the new ipxe.iso file?

Yeah, CI fails to build the `ipxe.iso` binary because of a missing binary. `util/genfsimg: could not find isolinux.bin`
PR to fix: https://github.com/tinkerbell/ipxedust/pull/69